version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ftm-db
    environment:
      POSTGRES_DB: ndsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./target/nds.sql:/docker-entrypoint-initdb.d/ndsdb.sq
    restart: always

  app:
    image: openjdk:17-jdk-slim
    container_name: ftm-app
    working_dir: /app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ndsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./target/ftm.jar:/app/ftm.jar
    ports:
      - "9090:9090"
    command: ["java", "-jar", "/app/ftm.jar"]
    restart: always

  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: swagger-ui
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SWAGGER_JSON=/usr/share/nginx/html/swagger.yaml
  #   volumes:
  #     - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
  #   depends_on:
  #     - app
  #   restart: always

volumes:
  db_data:
