version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ftm-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    networks:
      - ftm-network

  app:
    image: openjdk:17-jdk-slim
    container_name: ftm-app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./target/ftm.jar:/app/ftm.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/ftm.jar"]
    restart: always
    networks:
      - ftm-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.json
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/swagger.json
    ports:
      - "8081:8080"
    depends_on:
      - app
    restart: always
    networks:
      - ftm-network

volumes:
  db_data:

networks:
  ftm-network:
