openapi: 3.0.0
info:
  title: NDS API
  version: 1.0.0
  description: API for Users, Accounts, and Transactions
  contact:
    name: NDS API Team
    url: http://127.0.0.1:9090
servers:
  - url: http://127.0.0.1:9090
paths:
  /users/insert:
    post:
      summary: Insert a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: johndoe@example.com
                password:
                  type: string
                  example: password123
      responses:
        '200':
          description: User inserted successfully
  /users/list:
    get:
      summary: Find all users
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                      example: 0546e323-80c0-41e3-8e43-2deceb16661f
                    name:
                      type: string
                      example: John Doe
  /users/detail:
    post:
      summary: Get user details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 0546e323-80c0-41e3-8e43-2deceb16661f
      responses:
        '200':
          description: User details
  /users/update:
    post:
      summary: Update user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 0546e323-80c0-41e3-8e43-2deceb16661f
                name:
                  type: string
                  example: Ivan Tigris Sitohang
                email:
                  type: string
                  example: ivantigris@email.com
                created_at:
                  type: string
                  example: '2025-03-06T21:48:47.1511649'
      responses:
        '200':
          description: User updated successfully
  /users/delete:
    post:
      summary: Delete a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: c9b4009c-5260-41f6-9c64-2109ca272c8b
      responses:
        '200':
          description: User deleted successfully
  /accounts/insert:
    post:
      summary: Insert an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 0546e323-80c0-41e3-8e43-2deceb16661f
                balance:
                  type: number
                  example: 100000
      responses:
        '200':
          description: Account inserted successfully
  /accounts/list:
    get:
      summary: Find all accounts
      responses:
        '200':
          description: List of all accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    accountId:
                      type: string
                      example: a6d3dd51-862b-4beb-a72a-f4f063827f38
                    balance:
                      type: number
                      example: 100000
  /accounts/detail:
    post:
      summary: Get account details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: 0546e323-80c0-41e3-8e43-2deceb16661f
      responses:
        '200':
          description: Account details
  /accounts/find:
    post:
      summary: Find accounts by balance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                balance:
                  type: number
                  example: 500000
      responses:
        '200':
          description: Accounts found with the specified balance
  /transactions/insert:
    post:
      summary: Insert a transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                  example: a6d3dd51-862b-4beb-a72a-f4f063827f38
                type:
                  type: string
                  enum: [DEBIT, CREDIT]
                  example: DEBIT
                amount:
                  type: number
                  example: 100
      responses:
        '200':
          description: Transaction inserted successfully
  /transactions/list:
    get:
      summary: Pagination of transactions
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
            example: 0
        - in: query
          name: size
          required: true
          schema:
            type: integer
            example: 5
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                      example: 1d3e94d1-8646-4b6f-b6e9-43112a9d87f5
                    type:
                      type: string
                      example: DEBIT
                    amount:
                      type: number
                      example: 100
  /transactions/detail:
    post:
      summary: Get transaction details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                  example: a6d3dd51-862b-4beb-a72a-f4f063827f38
      responses:
        '200':
          description: Transaction details
  /transactions/report:
    post:
      summary: Get a transaction report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [DEBIT, CREDIT]
                  example: DEBIT
                startDate:
                  type: string
                  example: '2025-03-05'
                endDate:
                  type: string
                  example: '2025-03-10'
      responses:
        '200':
          description: Transaction report
